apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: kuberneteseg-a-mainapp
  name: kuberneteseg-a-mainapp
  namespace: kuberneteseg
spec:
  replicas: 2
  minReadySeconds: 45
  template:
    metadata:
      labels:
        app: kuberneteseg-a-mainapp
    spec:
      containers:
      - image: kapbhatnagar/kuberneteseg-a-mainapp
        imagePullPolicy: IfNotPresent
        name: kuberneteseg-a-mainapp
---
apiVersion: v1
kind: Service
metadata:
  labels: #PODS
    app: kuberneteseg-a-mainapp
  name: kuberneteseg-a-mainapp
  namespace: kuberneteseg
spec:
  type: LoadBalancer
  ports:
  - name: "8080"
    port: 8080 
    targetPort: 8080 
  selector:
    app: kuberneteseg-a-mainapp
  sessionAffinity: None 
  