From java:8
EXPOSE 8080
ADD target/kuberneteseg-b-java-emp-2-add-0.0.1-SNAPSHOT.jar kuberneteseg-b-java-emp-2-add-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","kuberneteseg-b-java-emp-2-add-0.0.1-SNAPSHOT.jar"]